# Generated by Django 5.0.7 on 2024-08-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
